#!/usr/bin/env python3
"""Generate 400 test data points from the factbook JSON files.

Outputs a Python list literal for use in test_data_points.py.
Each entry is (country_code, dot_path, expected_substring).
"""

import json
import random
import re
from pathlib import Path

DATA_DIR = Path("src/cia_world_factbook/data")
TARGET_COUNT = 400
SEED = 42  # reproducible


def normalize_key(key: str) -> str:
    s = key.strip().lower()
    s = s.replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "_", s)
    s = s.strip("_")
    if s and s[0].isdigit():
        s = "_" + s
    return s


def walk_paths(data: dict, prefix: str = "") -> list[tuple[str, str]]:
    """Walk JSON tree and collect (dot_path, text_value) pairs."""
    results = []
    for key, value in data.items():
        norm = normalize_key(key)
        path = f"{prefix}.{norm}" if prefix else norm
        if isinstance(value, dict):
            if "text" in value and isinstance(value["text"], str):
                results.append((f"{path}.text", value["text"]))
            results.extend(walk_paths(value, path))
        elif isinstance(value, str) and key == "text":
            pass  # already handled above
    return results


def extract_substring(text: str) -> str | None:
    """Extract a short, stable substring from a text value."""
    # Strip HTML tags
    clean = re.sub(r"<[^>]+>", "", text)
    clean = clean.strip()
    if not clean or len(clean) < 5:
        return None
    # Take a stable chunk (first 40 chars or first sentence)
    if len(clean) <= 50:
        return clean
    # Try to find a meaningful short phrase
    # Prefer content before a semicolon, comma-delimited chunk, etc.
    parts = clean.split(";")
    candidate = parts[0].strip()
    if 10 <= len(candidate) <= 60:
        return candidate
    # Just take first 45 chars
    return clean[:45]


def main():
    random.seed(SEED)

    # Collect all possible data points
    all_points: dict[str, list[tuple[str, str, str]]] = {}  # region -> [(code, path, text)]

    for region_dir in sorted(DATA_DIR.iterdir()):
        if not region_dir.is_dir():
            continue
        region = region_dir.name
        all_points[region] = []
        for json_file in sorted(region_dir.glob("[a-z][a-z].json")):
            code = json_file.stem
            with open(json_file, encoding="utf-8") as f:
                data = json.load(f)
            paths = walk_paths(data)
            for path, text in paths:
                sub = extract_substring(text)
                if sub:
                    all_points[region].append((code, path, sub))

    # Sampling strategy:
    # 1. Guarantee at least 3 from every region
    # 2. Guarantee at least 80 different countries
    # 3. Fill remaining with random selection, favoring diverse countries/sections

    selected: list[tuple[str, str, str]] = []
    used_codes: set[str] = set()

    # Phase 1: at least 3 per region
    for region, points in all_points.items():
        if not points:
            continue
        sample = random.sample(points, min(3, len(points)))
        for code, path, sub in sample:
            selected.append((code, path, sub))
            used_codes.add(code)

    # Phase 2: ensure 80+ different countries
    all_codes: dict[str, list[tuple[str, str, str]]] = {}
    for region, points in all_points.items():
        for code, path, sub in points:
            all_codes.setdefault(code, []).append((code, path, sub))

    unused_codes = [c for c in all_codes if c not in used_codes]
    random.shuffle(unused_codes)
    for code in unused_codes:
        if len(used_codes) >= 120:
            break
        points = all_codes[code]
        pick = random.choice(points)
        selected.append(pick)
        used_codes.add(code)

    # Phase 3: fill to TARGET_COUNT from all remaining points
    all_flat = []
    selected_set = {(c, p) for c, p, _ in selected}
    for region, points in all_points.items():
        for code, path, sub in points:
            if (code, path) not in selected_set:
                all_flat.append((code, path, sub))

    random.shuffle(all_flat)
    remaining = TARGET_COUNT - len(selected)
    if remaining > 0:
        # Prefer diverse sections
        selected.extend(all_flat[:remaining])

    # Sort for readability
    selected.sort(key=lambda x: (x[0], x[1]))

    # Output
    print("# Generated by scripts/generate_test_data.py")
    print(f"# {len(selected)} data points across {len(used_codes)}+ countries")
    print("DATA_POINTS = [")
    for code, path, sub in selected:
        # Escape quotes in substring
        sub_escaped = sub.replace("\\", "\\\\").replace('"', '\\"')
        print(f'    ("{code}", "{path}", "{sub_escaped}"),')
    print("]")


if __name__ == "__main__":
    main()
